CREATE TABLE IF NOT EXISTS system_settings (
  setting_key VARCHAR(60) PRIMARY KEY,
  value_json LONGTEXT NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS design_templates (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  kind ENUM('email','ticket') NOT NULL,
  name VARCHAR(120) NOT NULL,
  event_key VARCHAR(50) NULL,
  config_json LONGTEXT NOT NULL,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_template_event (event_key),
  INDEX idx_template_kind (kind)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS content_pages (
  slug VARCHAR(60) PRIMARY KEY,
  title VARCHAR(120) NOT NULL,
  body MEDIUMTEXT NOT NULL,
  published BOOLEAN NOT NULL DEFAULT FALSE,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

ALTER TABLE ticket_types ADD COLUMN IF NOT EXISTS template_id INT UNSIGNED NULL;
ALTER TABLE tickets ADD COLUMN IF NOT EXISTS design_snapshot LONGTEXT NULL;

CREATE TABLE IF NOT EXISTS mail_outbox (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  order_id INT UNSIGNED NOT NULL,
  event_key VARCHAR(50) NOT NULL,
  status ENUM('pending','sending','sent','failed','skipped') NOT NULL DEFAULT 'pending',
  attempts INT NOT NULL DEFAULT 0,
  error_message VARCHAR(500) NULL,
  message_id VARCHAR(255) NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_order_notification (order_id, event_key),
  INDEX idx_mail_pending (status, created_at),
  CONSTRAINT fk_mail_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
