-- Email templates — same schema as the hostel reference project
CREATE TABLE IF NOT EXISTS `email_templates` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `title` VARCHAR(100) DEFAULT NULL,
  `body` TEXT DEFAULT NULL,
  `body_2` TEXT DEFAULT NULL,
  `icon` VARCHAR(255) DEFAULT NULL,
  `logo` VARCHAR(255) DEFAULT NULL,
  `banner_image` VARCHAR(255) DEFAULT NULL,
  `button_name` VARCHAR(100) DEFAULT NULL,
  `button_url` VARCHAR(500) DEFAULT NULL,
  `footer_text` VARCHAR(255) DEFAULT NULL,
  `copyright_text` VARCHAR(100) DEFAULT NULL,
  `email_type` VARCHAR(100) DEFAULT NULL,
  `template_type` VARCHAR(50) DEFAULT 'user',
  `email_template` VARCHAR(10) DEFAULT '5',
  `privacy` TINYINT(1) DEFAULT 0,
  `refund` TINYINT(1) DEFAULT 0,
  `cancelation` TINYINT(1) DEFAULT 0,
  `contact` TINYINT(1) DEFAULT 0,
  `facebook` TINYINT(1) DEFAULT 0,
  `instagram` TINYINT(1) DEFAULT 0,
  `twitter` TINYINT(1) DEFAULT 0,
  `linkedin` TINYINT(1) DEFAULT 0,
  `pinterest` TINYINT(1) DEFAULT 0,
  `status` TINYINT(1) DEFAULT 1,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY `unique_type_email` (`email_type`, `template_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
