import { useEffect, useState } from 'react';
import api from '../../api/client';
import { Notice, errorText } from './StudioUI';
export default function DeliveryLog(){
  const [logs,setLogs]=useState([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(null),[message,setMessage]=useState(null);
  async function load(){setLoading(true);try{const {data}=await api.get('/admin/studio/mail-log');setLogs(data.data.logs);}catch(err){setMessage({text:errorText(err)});}finally{setLoading(false);}}
  useEffect(()=>{load();},[]);
  async function retry(log){if(!confirm(`Retry this ${log.event_key.replaceAll('_',' ')} email to ${log.email}? If delivery was interrupted, check whether it already arrived first.`))return;setBusy(log.id);setMessage(null);try{await api.post(`/admin/studio/mail-log/${log.id}/retry`);await load();setMessage({type:'success',text:'Queued. Delivery runs in the background; refresh to see the result.'});}catch(err){setMessage({text:errorText(err)});}finally{setBusy(null);}}
  return <><div className="studio-heading"><div><span className="studio-eyebrow">COMMUNICATIONS / DELIVERY</span><h1>Every message, accounted for.</h1><p>The latest 100 booking emails. “Sent” means accepted by your SMTP server.</p></div><button className="studio-button secondary" onClick={load} disabled={loading}>{loading?'Refreshing…':'Refresh'}</button></div><Notice message={message}/><div className="studio-panel studio-table-wrap"><table className="studio-table"><thead><tr><th>Booking / recipient</th><th>Notification</th><th>Status</th><th>Details</th><th>Action</th></tr></thead><tbody>{logs.map(log=><tr key={log.id}><td><strong>{log.booking_ref}</strong><small>{log.email}</small></td><td>{log.event_key.replaceAll('_',' ')}</td><td><span className={`studio-badge ${log.status==='sent'?'success':''}`}>{log.status}</span></td><td><small>{log.error_message || log.updated_at}<br/>{log.attempts} attempt(s)</small></td><td>{['failed','skipped'].includes(log.status) && <button className="studio-text-button" disabled={busy===log.id} onClick={()=>retry(log)}>{busy===log.id?'Queuing…':'Retry delivery'}</button>}</td></tr>)}</tbody></table>{!logs.length && <div className="studio-empty">{loading?'Loading deliveries…':'New booking emails will appear here. Configure SMTP to enable delivery.'}</div>}</div></>;
}
