import { useState } from 'react';
import api from '../../api/client';
import SocialLinksSettings from './SocialLinksSettings';
import { Field, Toggle, ImageField, Notice, Icon, errorText, useUnsaved } from './StudioUI';

export default function MailSettings({data,onSettings}) {
  const [brand,setBrand]=useState(data.brand);
  const [smtp,setSmtp]=useState({...data.smtp,password:''});
  const [saved,setSaved]=useState(JSON.stringify({brand:data.brand,smtp:{...data.smtp,password:''}}));
  const [busy,setBusy]=useState('');
  const [message,setMessage]=useState(null);
  useUnsaved(saved!==JSON.stringify({brand,smtp}));
  const change=(key,value)=>setSmtp(s=>({...s,[key]:value}));
  async function save(section,e){e.preventDefault();setBusy(section);setMessage(null);try{const {data:r}=await api.put(`/admin/studio/${section}`,section==='brand'?brand:smtp);if(section==='brand'){setBrand(r.data.brand);onSettings('brand',r.data.brand);setSaved(prev=>JSON.stringify({...JSON.parse(prev),brand:r.data.brand}));}else{const safe={...r.data.smtp,password:''};setSmtp(safe);onSettings('smtp',r.data.smtp);setSaved(prev=>JSON.stringify({...JSON.parse(prev),smtp:safe}));}setMessage({type:'success',text:r.message});}catch(err){setMessage({text:errorText(err)});}finally{setBusy('');}}
  async function verify(){setBusy('verify');setMessage(null);try{const {data:r}=await api.post('/admin/studio/smtp/verify');setMessage({type:'success',text:r.message});}catch(err){setMessage({text:errorText(err)});}finally{setBusy('');}}
  return <><div className="studio-heading"><div><span className="studio-eyebrow">CONFIGURATION / DELIVERY</span><h1>Make it yours. Send it reliably.</h1><p>Manage your brand, social profiles and email provider.</p></div><span className={`studio-badge ${data.smtp.enabled?'success':''}`}>{data.smtp.enabled?'Delivery enabled':'Delivery disabled'}</span></div><Notice message={message}/><div className="studio-settings-grid">
    <SocialLinksSettings links={data.socialLinks} onSave={socialLinks=>onSettings('socialLinks',socialLinks)}/>
    <form className="studio-panel" onSubmit={e=>save('brand',e)}><div className="studio-panel-title"><Icon name="ticket"/><h2>Brand identity</h2></div><div className="studio-form-body"><Field label="Company name" value={brand.company_name} required onChange={e=>setBrand({...brand,company_name:e.target.value})}/><Field label="Public website URL" type="url" value={brand.site_url} required hint="Used for ticket, image and policy links in emails. Use your public domain before sending to customers." onChange={e=>setBrand({...brand,site_url:e.target.value})}/><Field label="Support email" type="email" value={brand.support_email} onChange={e=>setBrand({...brand,support_email:e.target.value})}/><ImageField label="Default email logo" value={brand.logo} onChange={v=>setBrand({...brand,logo:v})}/><button className="studio-button primary" disabled={!!busy}>{busy==='brand'?'Saving…':'Save brand settings'}</button></div></form>
    <form className="studio-panel" onSubmit={e=>save('smtp',e)}><div className="studio-panel-title"><Icon name="mail"/><h2>Mail configuration</h2><span>SMTP</span></div><div className="studio-form-body"><Toggle label="Enable automatic emails" hint="Booking confirmations, cancellations and refunds use your active templates." checked={smtp.enabled} onChange={v=>change('enabled',v)}/><Field label="SMTP host" placeholder="smtp.example.com" required value={smtp.host} onChange={e=>change('host',e.target.value)}/><div className="studio-two-col"><Field label="Port" type="number" min="1" max="65535" required value={smtp.port} onChange={e=>change('port',Number(e.target.value))}/><Field label="Encryption"><select value={smtp.encryption} onChange={e=>{change('encryption',e.target.value);change('port',e.target.value==='tls'?465:587);}}><option value="starttls">STARTTLS · usually 587</option><option value="tls">TLS / SSL · usually 465</option></select></Field></div><Field label="Username" autoComplete="off" value={smtp.username} onChange={e=>change('username',e.target.value)}/><Field label="SMTP password" type="password" autoComplete="new-password" value={smtp.password} placeholder={smtp.has_password?'Password saved — leave blank to keep it':'Enter your SMTP password'} hint={smtp.has_password?'The saved password is encrypted and is never returned to the browser.':'Use the password or app password provided by your email service.'} onChange={e=>change('password',e.target.value)}/><div className="studio-two-col"><Field label="Sender name" required value={smtp.from_name} onChange={e=>change('from_name',e.target.value)}/><Field label="Sender email" type="email" required value={smtp.from_email} onChange={e=>change('from_email',e.target.value)}/></div><Field label="Reply-to email (optional)" type="email" value={smtp.reply_to} onChange={e=>change('reply_to',e.target.value)}/><div className="studio-tip">Save first, then verify the connection. Use “Send test” in Email templates to check how a message arrives.</div><div className="studio-save-bar"><button type="button" className="studio-button secondary" onClick={verify} disabled={!!busy}>{busy==='verify'?'Connecting…':'Verify saved connection'}</button><button className="studio-button primary" disabled={!!busy}>{busy==='smtp'?'Saving…':'Save SMTP settings'}</button></div></div></form></div></>;
}
