import { useState } from 'react';
import api from '../../api/client';
import { Field, RichEditor, Toggle, Notice, Icon, errorText, useUnsaved } from './StudioUI';
export default function Policies({data,onPage}) {
  const [page,setPage]=useState(() => data.pages.find(p => p.slug === 'privacy-policy') || data.pages[0]);
  const [saved,setSaved]=useState(JSON.stringify(page));
  const [message,setMessage]=useState(null);
  const [busy,setBusy]=useState(false);
  const allowChange=useUnsaved(saved!==JSON.stringify(page));
  async function save(e){e.preventDefault();setBusy(true);setMessage(null);try{const {data:r}=await api.put(`/admin/studio/pages/${page.slug}`,page);setPage(r.data.page);setSaved(JSON.stringify(r.data.page));onPage(r.data.page);setMessage({type:'success',text:r.message});}catch(err){setMessage({text:errorText(err)});}finally{setBusy(false);}}
  return <><div className="studio-heading"><div><span className="studio-eyebrow">CONTENT / POLICIES & PAGES</span><h1>Clarity builds confidence.</h1><p>Write your policies, keep them current, and publish when ready.</p></div></div><Notice message={message}/><div className="studio-policy-grid"><section className="studio-panel"><div className="studio-panel-title"><Icon name="page"/><h2>Your pages</h2></div><div className="studio-design-list">{data.pages.map(p=><button key={p.slug} className={p.slug===page.slug?'selected':''} onClick={()=>{if(!allowChange())return;setPage(p);setSaved(JSON.stringify(p));setMessage(null);}}><Icon name="page"/><div><strong>{p.title}</strong><small>{p.published?'Published':'Draft'}</small></div><span className={p.published?'studio-live-dot':'studio-muted-dot'}/></button>)}</div></section><form onSubmit={save} className="studio-panel"><div className="studio-panel-title"><h2>{page.title}</h2><span className="studio-badge">{page.published?'Published':'Draft'}</span></div><div className="studio-form-body"><Field label="Page title" value={page.title} required maxLength={120} onChange={e=>setPage({...page,title:e.target.value})}/><div className="studio-field"><span>Page content · CKEditor</span><RichEditor key={page.slug} label="Page content" placeholder={`Write your ${page.title.toLowerCase()}…`} value={page.body} onChange={body=>setPage(p=>({...p,body}))}/></div><div className="studio-tip">Describe your own business practices and contact details. Draft pages stay hidden from the website and email footers.</div><Toggle label="Publish this page" hint={`/pages/${page.slug}`} checked={page.published} onChange={published=>setPage({...page,published})}/><div className="studio-save-bar">{data.pages.find(p=>p.slug===page.slug)?.published && <a href={`/pages/${page.slug}`} target="_blank" rel="noreferrer" className="studio-button secondary"><Icon name="eye"/>View published page</a>}<button className="studio-button primary" disabled={busy}>{busy?'Saving…':page.published?'Save & publish':'Save draft'}</button></div></div></form></div></>;
}
