import { useState } from 'react';
import { Link } from 'react-router-dom';
import api from '../../api/client';
import DesignedTicket from '../../components/DesignedTicket';
import { Field, Toggle, ImageField, Notice, Icon, errorText, useUnsaved } from './StudioUI';

export default function TicketDesigner({ data, onUpdate }) {
  const [selected,setSelected]=useState(data.ticketTemplates[0] || {name:'My ticket design',kind:'ticket',active:true,config:{...data.defaults.ticket}});
  const [saved,setSaved]=useState(JSON.stringify(selected));
  const [message,setMessage]=useState(null);
  const [saving,setSaving]=useState(false);
  const allowChange=useUnsaved(JSON.stringify(selected)!==saved);
  const config=selected.config;
  const update=(key,value)=>setSelected(s=>({...s,config:{...s.config,[key]:value}}));
  function select(template) { if(!allowChange())return; setSelected(structuredClone(template));setSaved(JSON.stringify(template));setMessage(null); }
  function create(){select({name:'Untitled ticket design',kind:'ticket',active:true,config:{...data.defaults.ticket}});}
  async function save(e){e.preventDefault();setSaving(true);setMessage(null);try{const {data:r}=await api[selected.id?'put':'post'](`/admin/studio/templates${selected.id?'/'+selected.id:''}`,selected);setSelected(r.data.template);setSaved(JSON.stringify(r.data.template));onUpdate(r.data.template);setMessage({type:'success',text:'Design saved. Assign it to a ticket type under Events.'});}catch(err){setMessage({text:errorText(err)});}finally{setSaving(false);}}
  return <><div className="studio-heading"><div><span className="studio-eyebrow">DESIGN STUDIO / TICKETS</span><h1>Make an entrance.</h1><p>Create a ticket that feels like part of the experience.</p></div><button className="studio-button secondary" onClick={create}><Icon name="plus"/>New design</button></div>
    <div className="studio-workflow"><span><b>01</b> Design your ticket</span><i>→</i><Link to="/admin/events"><b>02</b> Assign to a ticket type</Link><i>→</i><span><b>03</b> Issued with every booking</span></div>
    <Notice message={message}/>
    <div className="studio-ticket-workspace"><section className="studio-panel"><div className="studio-panel-title"><Icon name="ticket"/><h2>Ticket collection</h2></div><div className="studio-design-list">{data.ticketTemplates.map(t=><button key={t.id} className={selected.id===t.id?'selected':''} onClick={()=>select(t)}><span style={{background:t.config.accent}}/><div><strong>{t.name}</strong><small>{t.config.layout} · {t.active?'Active':'Archived'}</small></div><Icon name="arrow" size={16}/></button>)}{!data.ticketTemplates.length && <p>Your saved designs will appear here.</p>}</div><div className="studio-tip">Start with a layout, add your branding, then save. QR codes and booking details are filled in automatically.</div></section>
    <form onSubmit={save} className="studio-panel studio-design-controls"><div className="studio-panel-title"><h2>Design details</h2><span>{selected.id?'Saved design':'New design'}</span></div><div className="studio-form-body"><Field label="Design name" value={selected.name} maxLength={120} required onChange={e=>setSelected({...selected,name:e.target.value})}/><Field label="Layout"><select value={config.layout} onChange={e=>update('layout',e.target.value)}><option value="classic">Classic admission ticket</option><option value="minimal">Minimal white ticket</option><option value="badge">Portrait event badge</option></select></Field><div className="studio-two-col"><Field label="Accent color"><div className="studio-color"><input type="color" value={config.accent} onChange={e=>update('accent',e.target.value)}/><code>{config.accent}</code></div></Field><Field label="Background"><div className="studio-color"><input type="color" value={config.background} disabled={config.layout==='minimal'} onChange={e=>update('background',e.target.value)}/><code>{config.layout==='minimal'?'#ffffff':config.background}</code></div></Field></div><Field label="Brand name" value={config.brand} required maxLength={120} onChange={e=>update('brand',e.target.value)}/><Field label="Eyebrow text" value={config.heading} maxLength={255} onChange={e=>update('heading',e.target.value)}/><div className="studio-two-col"><ImageField label="Logo" value={config.logo} onChange={v=>update('logo',v)}/><ImageField label="Banner" value={config.banner_image} onChange={v=>update('banner_image',v)}/></div><Field label="Entry instructions"><textarea rows={3} value={config.footer_text} maxLength={1000} onChange={e=>update('footer_text',e.target.value)}/></Field><Toggle label="Show attendee name" checked={config.show_attendee} onChange={v=>update('show_attendee',v)}/><Toggle label="Show ticket price" checked={config.show_price} onChange={v=>update('show_price',v)}/><Toggle label="Available for new tickets" hint="Existing tickets keep their saved design." checked={selected.active} onChange={v=>setSelected({...selected,active:v})}/><button className="studio-button primary" disabled={saving}>{saving?'Saving…':'Save ticket design'}<Icon name="check"/></button></div></form>
    <section className="studio-ticket-preview"><div className="studio-preview-label"><span className="studio-live-dot"/>LIVE PREVIEW <span>Sample booking</span></div><DesignedTicket design={config} preview/><p><Icon name="check" size={14}/>Unique QR codes are generated when tickets are issued.</p></section></div></>;
}
